### ISSUE TITLE
I see new cproj implementation

### ISSUE THREAD

**Issue by yuki-kimoto** [kraj/glibc#2]
Hi

Is this glibc public repository?

I'm SPVM programing language author. This is C transpiler from Perl syntax.

https://github.com/yuki-kimoto/SPVM

I have one problem.

Old glibc cproj, cprojf is different from new implementation of cproj, cprojf.

I provide new cproj, cprojf on SPVM in old glibc.

If I can know, I want to know the version check way and see cproj implementation.

**Comment by kraj** [comment]
@yuki-kimoto this is my fork that I keep especially for Openembedded/Yocto work. Upstream is not on github but here [1]

[1] https://www.gnu.org/software/libc/sources.html

**Comment by yuki-kimoto** [comment]
@kraj 

thank you!
